// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIiJbWbntM_E3i-Ex1UyordT2zp1OmWSk',
    appId: '1:644499023081:web:5eaecb7ffa88ba769abc78',
    messagingSenderId: '644499023081',
    projectId: 'elite-customer-8b70c',
    authDomain: 'elite-customer-8b70c.firebaseapp.com',
    storageBucket: 'elite-customer-8b70c.firebasestorage.app',
    measurementId: 'G-SKGPL0Y6Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjaS9eTkxOipZDuUupShSKwghKp8eD9o',
    appId: '1:644499023081:android:0f7a05083f0513959abc78',
    messagingSenderId: '644499023081',
    projectId: 'elite-customer-8b70c',
    storageBucket: 'elite-customer-8b70c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl502riXGXW8OL8SxqSDMqr1ttqiTKA0E',
    appId: '1:644499023081:ios:b8928e24cff0c5f89abc78',
    messagingSenderId: '644499023081',
    projectId: 'elite-customer-8b70c',
    storageBucket: 'elite-customer-8b70c.firebasestorage.app',
    iosBundleId: 'com.example.eliteCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl502riXGXW8OL8SxqSDMqr1ttqiTKA0E',
    appId: '1:644499023081:ios:b8928e24cff0c5f89abc78',
    messagingSenderId: '644499023081',
    projectId: 'elite-customer-8b70c',
    storageBucket: 'elite-customer-8b70c.firebasestorage.app',
    iosBundleId: 'com.example.eliteCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIiJbWbntM_E3i-Ex1UyordT2zp1OmWSk',
    appId: '1:644499023081:web:3354f1cdf6009a929abc78',
    messagingSenderId: '644499023081',
    projectId: 'elite-customer-8b70c',
    authDomain: 'elite-customer-8b70c.firebaseapp.com',
    storageBucket: 'elite-customer-8b70c.firebasestorage.app',
    measurementId: 'G-E8HRN33E8P',
  );
}
